---

- name: "check git {{ config.option }}"
  command: git config --global --get "{{ config.option }}"
  changed_when: no
  failed_when: no
  register: t_git_config_check

- name: "set git config {{ config.option }} to {{ config.value }}"
  command: "git config {{ config.scope|d('--global') }} {{ config.option }} {{ config.value }}"
  when: t_git_config_check.rc != 0 or t_git_config_check.stdout != config.value
