---

- name: install required packages
  include: install_packages.yml
  vars: {
    packages: "{{ gitlab_prereq_packages }}",
    services: []
  }

- name: install Git
  include: install_git.yml
  become: yes
  become_user: "{{ gitlab_user }}"

- name: install Ruby
  include: install_ruby.yml
  become: yes
  become_user: "{{ gitlab_user }}"

- name: install Go
  include: install_go.yml
  become: yes
  become_user: "{{ gitlab_user }}"
