---

- name: install required packages
  include: install_packages.yml
  vars: {
    packages: "{{ gitlab_prereq_packages }}",
    services: []
  }

- name: install Git
  include: install_git.yml

- name: install Ruby
  include: install_ruby.yml
