---

- name: check standard git package
  block:
    - name: get git version
      shell: git --version | cut -d ' ' -f3
      changed_when: false
      register: t_gitlab_git_version

    - name: set gitlab_git_version_valid
      set_fact:
        gitlab_git_version_valid: "{{ t_gitlab_git_version.stdout is version('2.22.0', '>=') }}"

    # FIXME: clean
    - debug:
        msg: "{{ t_gitlab_git_version.stdout }}"

    # FIXME: clean
    - debug:
        msg: "{{ gitlab_git_version_valid }}"

    - name: check git shared object dependency with pcre2
      shell: ldd `which git` | grep pcre2
      changed_when: false
      failed_when: false
      register: t_gitlab_git_pcre2_dep

    # FIXME: clean
    - debug:
        msg: "{{ t_gitlab_git_pcre2_dep.rc }}"
