---

## service architecture
# https://docs.gitlab.com/ee/development/architecture.html
## backup
# https://docs.gitlab.com/ee/raketasks/backup_restore.html

- block:
    - include: context.yml

    - include: accounts.yml
      vars: {
        accounts_groups: "{{ gitlab_groups }}",
        accounts_users: "{{ gitlab_users }}"
      }

    - include: workspace.yml

    - include: install.yml

    # - include: setup_db.yml

    - include: setup_redis.yml

    - include: git_configs.yml

    - include: setup_gitlab.yml

    - include: setup_gitlab_shell.yml

    - include: setup_gitlab_workhorse.yml

    # - include: service.yml

  when: want_gitlab

- name: "set has_gitlab to {{ want_gitlab }}"
  set_fact:
    has_gitlab: "{{ want_gitlab }}"
