---

## service architecture
# https://docs.gitlab.com/ee/development/architecture.html
## backup
# https://docs.gitlab.com/ee/raketasks/backup_restore.html

- block:
    - include: context.yml

    - include: accounts.yml
      vars: {
        accounts_groups: "{{ gitlab_ce_groups }}",
        accounts_users: "{{ gitlab_ce_users }}"
      }

    - include: workspace.yml

    - include: install.yml

    # - include: setup.yml

    # - include: service.yml

  when: want_gitlab

- name: "set has_gitlab to {{ want_gitlab }}"
  set_fact:
    has_gitlab: "{{ want_gitlab }}"
