---
## install
# https://docs.gitlab.com/12.9/ee/install/installation.html
## service architecture
# https://docs.gitlab.com/ee/development/architecture.html
## backup
# https://docs.gitlab.com/ee/raketasks/backup_restore.html

- block:
    - include: context.yml

    - include: accounts.yml
      vars: {
        accounts_groups: "{{ gitlab_groups }}",
        accounts_users: "{{ gitlab_users }}"
      }

    - include: workspace.yml

    - include: install.yml

    - include: certificates.yml

    - include: setup_db.yml

    - include: setup_redis.yml

    - include: git_configs.yml

    - include: setup_gitlab.yml

    - include: setup_gitlab_shell.yml

    - include: setup_gitlab_workhorse.yml

    # disable, because not available in public version
    # - include: setup_gitlab_elasticsearch_indexer.yml

    - include: setup_gitlab_pages.yml

    - include: setup_gitaly.yml

    - include: setup_gitlab_postinstall.yml

    # FIXME: implement log rotation
    # - include: setup_log_rotate.yml

    - include: compile_assets.yml

    - include: setup_gitlab_services.yml

    - include: setup_gitlab_checks.yml

    - include: setup_nginx.yml

  when: want_gitlab

- name: "set has_gitlab to {{ want_gitlab }}"
  set_fact:
    has_gitlab: "{{ want_gitlab }}"
