---

- name: stat gitlab-pages bin
  stat:
    path: "{{ gitlab_pages_dir }}/bin/gitlab-pages"
  register: t_gitlab_pages_bin_stat

- block:
    - name: clean gitlab-pages dir
      file:
        path: "{{ gitlab_pages_dir }}"
        state: absent

    - name: get required gitlab-pages version
      command: "cat {{ gitlab_gitlab_dir }}/GITLAB_PAGES_VERSION"
      changed_when: no
      register: t_gitlab_pages_version

    - name: checkout gitlab-pages repository
      git:
        repo: "{{ gitlab_pages_repository }}"
        dest: "{{ gitlab_pages_dir }}"
        version: "v{{ t_gitlab_pages_version.stdout }}"
        accept_hostkey: yes
        umask: "022"
        force: yes
      register: t_gitlab_pages_checkout

    - name: build gitlab-pages
      command: "make -j {{ ansible_processor_vcpus|d(ansible_processor_count) }}"
      args:
        chdir: "{{ gitlab_pages_dir }}"
      environment:
        PATH: "{{ gitlab_PATH }}"

  become: yes
  become_user: "{{ gitlab_user }}"
  when: not t_gitlab_pages_bin_stat.stat.exists
