---

# Not working when using copy, template
# - block:
#   become: yes
#   become_user: "{{ gitlab_user }}"

- name: stat gitlab-shell bin
  stat:
    path: "{{ gitlab_shell_dir }}/bin/gitlab-shell"
  register: t_gitlab_shell_bin_stat


- block:

    - name: clean gitlab-shell dir
      file:
        path: "{{ gitlab_shell_dir }}"
        state: absent

    - name: recreate gitlab-shell dir
      file:
        path: "{{ gitlab_shell_dir }}"
        owner: "{{ gitlab_user }}"
        group: "{{ gitlab_group }}"
        mode: "0750"
        state: directory

    - name: get required gitlab-shell version
      command: "cat {{ gitlab_gitlab_dir }}/GITLAB_SHELL_VERSION"
      changed_when: no
      register: t_gitlab_shell_version

    - name: checkout gitlab-shell repository
      git:
        repo: "{{ gitlab_shell_repository }}"
        dest: "{{ gitlab_shell_dir }}"
        version: "v{{ t_gitlab_shell_version.stdout }}"
        accept_hostkey: yes
        umask: "022"
        force: yes
      register: t_gitlab_shell_checkout
      become: yes
      become_user: "{{ gitlab_user }}"

  when: not t_gitlab_shell_bin_stat.stat.exists


- name: setup workspace directory tree
  file:
    path: "{{ item.path | d(omit) }}"
    src: "{{ item.src | d(omit) }}"
    dest: "{{ item.dest | d(omit) }}"
    owner: "{{ item.owner | d(omit) }}"
    group: "{{ item.group | d(omit) }}"
    mode: "{{ item.mode | d(omit) }}"
    state: "{{ item.state|d('directory') }}"
  loop: "{{ gitlab_shell_directories }}"


- block:
    - name: bundle install
      command: "bundle install -j{{ ansible_processor_vcpus|d(ansible_processor_count) }}"
      args:
        chdir: "{{ gitlab_shell_dir }}"
      environment:
        PATH: "{{ gitlab_PATH }}"

    - name: build gitlab-shell
      command: "make -j {{ ansible_processor_vcpus|d(ansible_processor_count) }} build"
      args:
        chdir: "{{ gitlab_shell_dir }}"
      environment:
        PATH: "{{ gitlab_PATH }}"

    - name: call standard rake task
      command: "bundle exec rake gitlab:shell:install REDIS_URL=unix:{{ gitlab_redis_socket }} RAILS_ENV=production SKIP_STORAGE_VALIDATION=true"
      args:
        chdir: "{{ gitlab_gitlab_dir }}"
      environment:
        PATH: "{{ gitlab_PATH }}"

  become: yes
  become_user: "{{ gitlab_user }}"
  when: not t_gitlab_shell_bin_stat.stat.exists


- name: deploy gitlab-shell config.yml
  template:
    src: gitlab-shell/config.yml
    dest: "{{ gitlab_shell_dir }}/config.yml"
    mode: "0644"
    owner: "{{ gitlab_user }}"
    group: "{{ gitlab_group }}"
