---

- name: deploy check scripts
  template:
    src: "gitlab/bin/{{ item }}"
    dest: "{{ gitlab_bin_dir }}/{{ item }}"
    mode : "0755"
    owner: "{{ gitlab_user }}"
    group: "{{ gitlab_group }}"
  loop:
    - check
    - env_info

- name: run gitlab check
  shell: "{{ gitlab_bin_dir }}/check"
  changed_when: false
  register: t_gitlab_check
  become: yes
  become_user: "{{ gitlab_user }}"

- debug:
    msg: "{{ t_gitlab_check }}"
