---

- name: stat gitaly bin
  stat:
    path: "{{ gitlab_gitaly_dir }}/gitaly"
  register: t_gitlab_gitaly_bin_stat


- block:
    - name: install gitaly
      shell: "bundle exec rake 'gitlab:gitaly:install[{{ gitlab_gitaly_dir }},{{ gitlab_repositories_dir }}]' RAILS_ENV=production"
      args:
        chdir: "{{ gitlab_gitlab_dir }}"
      environment:
        PATH: "{{ gitlab_build_PATH }}"
      become: yes
      become_user: "{{ gitlab_user }}"

  when: not t_gitlab_gitaly_bin_stat.stat.exists

- name: deploy gitaly config.toml
  template:
    src: "gitaly/{{ item.name }}"
    dest: "{{ gitlab_gitaly_dir }}/{{ item.name }}"
    mode: "{{ item.mode }}"
    owner: "{{ gitlab_user }}"
    group: "{{ gitlab_group }}"
  loop:
    - { name: config.toml, mode: "0644" }
  register: t_gitlab_gitaly_conf
