#!/bin/sh

export PATH="{{ gitlab_tools_PATH }}:{{ gitlab_gitlab_PATH }}:/usr/local/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin"

exec 2>&1

APP_USER="{{ gitlab_user }}"
APP_USER_HOME="{{ gitlab_git_home }}"
APP_ROOT="{{ gitlab_gitlab_dir }}"
APP_SOCKET="{{ gitlab_gitlab_socket }}"
APP_AUTH_BACKEND="{{ gitlab_gitlab_auth_backend }}"
WORKHORSE_SOCKET="{{ gitlab_workhorse_socket }}"

workhorse_args="-listenUmask 0 -listenNetwork unix -listenAddr $WORKHORSE_SOCKET -authBackend $APP_AUTH_BACKEND -authSocket $APP_SOCKET -documentRoot $APP_ROOT/public"

cd "$APP_ROOT" || exit 1

exec setuidgid "$APP_USER" \
     env PATH="{{ gitlab_workhorse_dir }}:$PATH" HOME="$APP_USER_HOME" \
     "{{ gitlab_workhorse_dir }}/gitlab-workhorse" $workhorse_args
