#!/bin/sh

export PATH="{{ gitlab_tools_PATH }}:/usr/local/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin"

exec 2>&1

APP_USER="{{ gitlab_user }}"
APP_USER_HOME="{{ gitlab_git_home }}"
APP_ROOT="{{ gitlab_gitlab_dir }}"
APP_WEB_SERVER="{{ gitlab_gitlab_web_server }}"
APP_SOCKET="{{ gitlab_gitlab_sockets_dir }}/gitlab.socket"
APP_ENV=production

set -e

cd "$APP_ROOT"
rm -f "$APP_SOCKET"

exec setuidgid "$APP_USER" \
     env RAILS_ENV="$APP_ENV" USE_WEB_SERVER="$APP_WEB_SERVER" HOME="$APP_USER_HOME" \
     "$APP_ROOT/bin/web" start_foreground
